from distutils.core import setup
setup(name='Appalachian Tech',
          version='1.0',
          py_modules=['script', 'webbrowseropener'],
          classifiers=[
              'Development Status :: 4 - Beta',
              'Environment :: Console',
              'Environment :: Web Environment',
              'Intended Audience :: End Users/Desktop',
              'Intended Audience :: Developers',
              'Intended Audience :: System Administrators',
              'License :: OSI Approved :: Python Software Foundation License',
              'Operating System :: MacOS :: MacOS X',
              'Operating System :: Microsoft :: Windows',
              'Operating System :: POSIX',
              'Programming Language :: Python',
              'Topic :: Communications :: Email',
              'Topic :: Office/Business',
              'Topic :: Software Development :: Bug Tracking',
              ],
          packages=['Appsoft'],
          package_dir={'Appsoft': 'src/Appsoft'},
          package_data={'appsoft': ['data/*.dat']},
          )
